services: docker
git:
  depth: false
install: make docker-login build-docker
stages:
- name: publish-docker
jobs:
  include:
  - stage: publish
    name: Publish docker image
    script:
    - make docker-login publish-docker
env:
  global:
  - secure: fWpiSreL6OGytIjzVWic+i6ckLpSNPwzGTVM/BSZNyyeHogk9O6N7UEn8/lasGq7nr0c/xNYwulR9fRSKdJzfoHCeWqDeD3Tn1sE3zx3qDtzqxc7hU5cydId3npYns8QWo+ZgQppfjzevAsteGuiqyAbjrPEYyReeOOqepyfke+uEr5GvapbNPNTQRdgol2wxvhziznZ03iw1x05c6b8GvhzUOIZv028S7wgRr51qhaZwpPned6OPd+X7XXxBNTiX0P68xY+P4nHxAK/DabkfWH/jWoC5ib0zMfLy+64psql/kVGTBc7ArEN+fuM2jn6vP7QFIIOvEbaYHFxE/t2c4T8mp5NeXZcYYzhGViilWECFzUaAaEVH3hgmBjvdW7rCzx3/33oVWDjRFwRViSDBpX8RgZs+DvnHcQtvYXu1q2F35FEe191gbEC6sQr9TDNn+dZUQX51Ye+Ho2zrwav4dWtZYkvWnyxuibXbTN08uaGEi+9B6indlqmmdEFyHBEr5Ms435enea6JeuNxByVmnCoyXIA1vLq9fSOkwp8zDntf/BuELAwMCdzGsjT3KldbHTYeS7ugXad3SDdFZ1TBUB9wirKOvcRbDibqbq2WH1PK2K/gkcMdEiUvw/GqZmLIMYpMKd6ZFxztFPRIEf2/kUdHaq2cFQhQH1feeeM7Kg=
  - secure: aG4IX6z9Y5j0L+WaV9jkQk8RxcRqRPigb+7QFhq1wm4+9WKfuTHDa4IoaRXuf8OAzTl+C7dz6l1qhBgYGcjPEHx2Yf357hz1nuX6GinHxt4bJk3wAXhaX8hVoyRiTFwqFzEBoXn3oR82dsN4Tusu5YTEFi2PLGt1JUAdIttMamIHEijm30AVzS1m3XlveH1I/OjGR843Ff34AC9PRgVGharkY8AIMOUAKQQZFzQiJQjqwDRehGzoJlKNxLrrw6Wj0R4KHVCRQhFQLmpqGdJmfdEP7MwNMH2/seZqppZqD6l6Vy7wwuE07TTEQUW9BqxkyWBccvnHZbs2h961+1QGOBi+A4q9VkPjtftiIrgaQNqal28cMLS7VDxqwqCWUte0riCqJlNmbayUvAJUBX14GdeAJuR4p47COmA7QwgJS/U1QXd6lKDpPlcJllwVStH45/GGHOqoCXwS3C46ngiRT2m+PvRFOTpParmbZT54ZHsqw+J60zTU9d1UhgPR6ReJUDIivJuck3VkNpyZ7Y7YwHyJ+zy/I9THh37AOXRfUveupfV727FMgihZeUlQU6vuZZjQAQSDXl9qjOKZVfUnb/u8IgWfeYlMWCUOvA7wXx+aLGGGHMiDLp1SI9M6qWSsAlRCzG90CsG7+1gE3T1di/qsyTCayjBlv4TjL60dkzw=
